### PR TITLE
Add `perldoc` to list of `less`-like commands (touchscreen interaction)

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
## Summary
 * While #246 had `less` and `man` and `... | less` in the list of `less`-like commands, it didn't have `perldoc`! This PR adds `perldoc` to the list of `less`-like commands.
 * Having to maintain a list of `less` and `vim`-like commands isn't ideal...
   * Using `window.interactiveCommandRunning` won't work for this. Commands like `ipython` and `jsi` should have normal scrolling behavior, but are still marked interactive and `perldoc` isn't marked interactive!

### CODE REVIEW

**Comment by holzschu** [comment]
Good question. Basically, "less-like commands" are commands that are interactive, but don't use cursor-position requests. They usually use `openpty` to get keyboard input. So we have ways to find them. Except perldoc is not in the list for interactive commands:
https://github.com/holzschu/a-shell/blob/cb8eb579d7284091fcf6bed59fd49a124a7e7ba7/script.js#L46

So how did it get its interactive status? I cannot remember.

**Comment by personalizedrefrigerator** [comment]
I think `perldoc` and `man` work with and without window.interactiveCommandRunning = true`... 
<details>
<summary>(Results from toggling interactive mode with this script)</summary>

```js
//jsc --in-window

(function() {
  if (!window.term_)
  {
    print_error("Must be run in the terminal's context");
    exit(1);
  }

  if (!window.interactiveToggle)
  {
    window.interactiveToggle = {};
    window.term_.document_.body.addEventListener("keydown",
      (evt) => window.interactiveToggle.keyListener(evt),
      true);
    window.term_.document_.addEventListener("scroll",
      (evt) => window.interactiveToggle.scrollListener(evt));
    window.term_.document_.addEventListener("selectionchange",
      (evt) => window.interactiveToggle.selectionChangeListener(evt));
    window.term_.document_.body.addEventListener("pointerdown",
      (evt) => window.interactiveToggle.pointerDownListener(evt), true);
    window.term_.document_.body.addEventListener("pointermove",
      (evt) => window.interactiveToggle.pointerMoveListener(evt), true);
    window.term_.document_.body.addEventListener("pointerup",
      (evt) => window.interactiveToggle.pointerUpListener(evt), true);
    window.addEventListener("error",
      (evt) => window.interactiveToggle.globalErrorListener(evt), true);

    interactiveToggle.display = document.createElement("div");
    document.body.appendChild(interactiveToggle.display);

    interactiveToggle.styleSheet = document.createElement("style");
    document.body.appendChild(interactiveToggle.styleSheet);

    setInterval(() => window.interactiveToggle.updateDisplayColor(), 250);
  }

  let display = interactiveToggle.display;
  display.style = `
    position: fixed;
    z-index: 999;
    top: 0;
    right: 0;
    max-width: 25vw;
    max-height: 25vh;
    background-color: white;
    padding: 3px;

    border-bottom-left-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.4);
    opacity: 0.5;

    transition: 0.1s ease all;
`;

  interactiveToggle.styleSheet.innerHTML =
  `
  @keyframes fadeToggle
  {
    0% { text-shadow: 4px 0px 10px rgba(255, 0, 0, 0.8); };
    40% { text-shadow: 4px 0px 40px rgba(200, 0, 200, 0.9); };
    100% { text-shadow: 4px 0px 10px rgba(255, 255, 0, 0.0); };
  }

  `;

  let displayUpdatesPausedUntil = -1;

  /// Display [newText] for at least [?showForAtLeast] seconds.
  const showMessage = (newText, showForAtLeast) =>
  {
    const nowTime = (new Date()).getTime();
    if (nowTime < displayUpdatesPausedUntil)
    {
      return;
    }

    if (showForAtLeast !== undefined)
    {
      display.style.animation = '';
      requestAnimationFrame(() =>
      {
        display.style.animation = "fadeToggle " + showForAtLeast + "s ease 1";
      });

      displayUpdatesPausedUntil = nowTime + showForAtLeast * 1000;
    }

    display.innerText = newText;
  };

  interactiveToggle.updateDisplayColor = () =>
  {
    if (window.interactiveCommandRunning)
    {
      display.style.backgroundColor = "rgba(255, 200, 200, 0.8)";
    }
    else
    {
      display.style.backgroundColor = "rgba(255, 255, 255, 0.8)";
    }
  };

  display.innerHTML = "...";
  interactiveToggle.keyListener = (evt) =>
  {
    let message = "Key: ";
    message += evt.key;

    if (evt.altKey)
    {
      message += " (ALT)";
    }

    if (evt.ctrlKey)
    {
      message += " (CTRL)";
    }

    if (evt.ctrlKey && evt.key == "i")
    {
      window.interactiveCommandRunning = !window.interactiveCommandRunning;
    }

    interactiveToggle.updateDisplayColor();
    showMessage(message);
  };

  display.onclick = () =>
  {
    window.interactiveCommandRunning = !window.interactiveCommandRunning;
    interactiveToggle.updateDisplayColor();
    showMessage("Cmd: " + window.commandRunning);
  };

  interactiveToggle.selectionChangeListener = (evt) =>
  {
    let message = "Sel: " + Math.floor(evt.timeStamp);
    showMessage(message);
    window.selEvent = evt;
  };

  interactiveToggle.pointerDownListener = (evt) =>
  {
    showMessage("Pointer down.");
  };

  interactiveToggle.pointerMoveListener = (evt) =>
  {
    showMessage("Pointer move.");
  };

  interactiveToggle.pointerUpListener = (evt) =>
  {
    showMessage("Pointer up.");
  };

  interactiveToggle.scrollListener = (evt) =>
  {
    showMessage("Scroll: ");
  };

  interactiveToggle.globalErrorListener = (evt) =>
  {
    showMessage("Error: " + evt.message + "; " + evt.stack, 1);

    window.lastError = evt;
  };

})();

```

</details>

Alternatively, `hterm` sometimes decides to interpret scroll-wheel events as arrow keys:

https://github.com/holzschu/a-shell/blob/cb8eb579d7284091fcf6bed59fd49a124a7e7ba7/hterm_all.js#L17970-L17972

Perhaps doing something similar to this would work.

**Comment by holzschu** [comment]
Well, all less-like commands are using an alternate screen (for now).

**Comment by personalizedrefrigerator** [comment]
> Well, all less-like commands are using an alternate screen (for now).

In #248, I've made the test for whether to do arrow-key scrolling (on vertical swipe) be whether the command is using an alternate screen.

The additional disabling of horizontal arrow-key gestures is still based on the command name, however.

**Comment by holzschu** [comment]
> So how did it get its interactive status? I cannot remember.
I remembered.
It's not `interactiveCommandRunning`, it's a separate mechanism: if a command starts a pager (less or more), or calls `openpty`, then it grabs the keyboard input. It's tested in the Swift / C side by calling the function `ios_activePager()`.

But to detect things on the JavaScript side, the safest thing is the fact that all pagers (and Vim) are running in the alternate screen.

**Pull request merged**
