### PR TITLE
Touchscreen gestures: Inertial scrolling and cursor movement

### LINKED ISSUE #231: Feature Request/WIP: Kinetic/Inertial Scrolling and Touch Scrolling in Vim
## Summary
 * It would be really nice to have inertial scrolling in a-Shell!

## Prototype
<details>

```js
// Run with jsc --in-window filename.js

// Destroy overlay if it already exists.
if (window.ttOverlay) {
    window.ttStatusArea.remove();
    window.ttOverlay.remove();
    window.ttOverlay = undefined;
    window.ttOverlayStyleSheet.remove();
    window.ttOverlayStyleSheet = undefined;
    term_.document_.removeEventListener("selectionchange", window.ttOverlaySelListener);
}

// Use our own scope.
(function() {
    // Set to true to enable debugging-specific UI.
    const DEBUG = false;

    window.ttStatusArea = term_.document_.createElement("div");
    window.ttOverlay = term_.document_.createElement("div");
    window.ttOverlayStyleSheet = term_.document_.createElement("style");

    const preSpace = term_.document_.createElement("div");
    const content = term_.document_.createElement("textarea");
    const postSpace = term_.document_.createElement("div");

    ttOverlay.appendChild(preSpace); // Appropriate sized scrollback
    ttOverlay.appendChild(content);  // Text overlay
    ttOverlay.appendChild(postSpace);// Appropriate sized scroll-forward

    // Rather than refreshing a textarea's contents with the entire scrollback
    // whenever the screen updates, only update a screenfull of text and fill
    // the rest of the scrollport with invisible divs.
    preSpace.classList.add("ttOverlaySpacer");
    postSpace.classList.add("ttOverlaySpacer");

    content.style = `
line-height: inherit;

padding: 0;
margin: 0;

/*
 Scrolling should scroll the contents of
 ttOverlay, not the textarea.
 */
overflow-y: hidden;
overflow-x: hidden;

outline: none;
border-radius: 0px;
background-color: transparent;

/* Inherit some settings from ttOverlay. */
color: inherit;
font: inherit;

display: block;
border: none;
padding: 0;
margin: 0;

/*
 Making the height 100.1vh helps prevent touch scrolling
 from scrolling the textarea instead of ttOverlay.
 */
width: 200vw;
height: 100.1vh;
    `;

    ttOverlayStyleSheet.innerHTML = `
x-screen *, x-screen {
    caret-color: transparent !important;
}

.ttOverlaySpacer {
    ${DEBUG ? "outline: 1px solid red;" : ""}
}

* {
    ${DEBUG ? "outline: 1px solid rgba(0, 0, 255, 0.4);" : ""}
}
    `;

    // Displays debug information.
    ttStatusArea.style = `
position: fixed;
top: 0;
left: 0;
z-index: 13;
background-color: gray;
color: white;
border-bottom-right-radius: 5px;
box-shadow: 0px 2px 2px #777;
padding: 3px;
max-width: 25vw;
max-height: 25vh;
opacity: 0.5;
${DEBUG ? "" : "display: none;"}
    `;

    ttOverlay.style = `
position: fixed;
top: 0;
left: 0;
right: 0;
bottom: 0;
overflow-y: scroll;
overflow-x: hidden;

/*
 Prevent word wrapping.
 See https://stackoverflow.com/questions/4652654/how-to-turn-off-word-wrapping-in-html
 */
word-wrap: unset;
overflow-wrap: unset;
word-break: unset;

/*
 We'll be displaying one screenfull of text at a time.
 Scroll within this.
 */
width: 100vw;
height: 100vh;

padding: 0;
z-index: 12;

background: transparent;

/* If debugging, make the overlay visible. */
color: ${DEBUG ? "rgba(0, 255, 255, 0.3)" : "transparent"};
    `;

    const getLineHeight = () => {
        return term_.scrollPort_.characterSize.height;
    };

    /**
     * Update the text in the overlay and the overlay's textbox's
     * position.
     */
    const updateTextarea = () => {
        let val = [];

        let charHeight = getLineHeight();
        let startRow = Math.floor(ttOverlay.scrollTop / charHeight);
        let endRow = Math.floor((ttOverlay.scrollTop + ttOverlay.clientHeight) / charHeight);

        for (let i = startRow; i < endRow; i++) {
            val.push(term_.getRowText(i));
        }

        content.value = val.join("\n");

        ttOverlay.style.fontFamily = term_.getFontFamily();
        ttOverlay.style.fontSize = term_.getFontSize();

        postSpace.style.height = (term_.getRowCount() - endRow) * charHeight + "px";
        preSpace.style.height = startRow * charHeight + "px";
    };

    let lastScrollTime = 0;

    /**
     * Update the textarea and make the overlay's scroll match the
     * terminal's scroll (if we're not being scrolled by the user).
     */
    const updateOverlay = () => {
        if ((new Date()).getTime() - lastScrollTime > 100) {
            updateTextarea();

            ttOverlay.scrollTop = term_.scrollPort_.screen_.scrollTop;
            ttOverlay.scrollLeft = 0;
        }
    };

    /*
     When the user's cursor moves or attempts to select text,
     update the contents of the overlay -- it is what the user will use to
     select text.

     TODO: What if the user wants to select more than a screenfull of text?
     */
    window.ttOverlaySelListener = term_.document_.   addEventListener("selectionchange", (evt) => {
        updateOverlay();
    });

    ttOverlay.onpointerdown = (evt) => updateOverlay();

    ttOverlay.onscroll = (evt) => {
        window.scrollEvt = evt;
        updateTextarea();
        lastScrollTime = (new Date()).getTime();

        let scrollTop = ttOverlay.scrollTop;
        let pxPerLine = getLineHeight();
        let termScrollTop = term_.scrollPort_.screen_.scrollTop;

        if (pxPerLine == 0) {
            return;
        }

        if (scrollTop > term_.scrollPort_.screen_.scrollHeight) {
            updateOverlay();
            return;
        }

        let deltaScroll = (scrollTop - termScrollTop) / pxPerLine;
        if (Math.round(Math.abs(deltaScroll)) == 0) {
            return;
        }

        ttStatusArea.innerHTML = Math.floor(deltaScroll);

        for (let i = 0; i < deltaScroll; i++) {
            term_.scrollLineDown();
        }

        for (let i = 0; i > deltaScroll; i--) {
            term_.scrollLineUp();
        }
    };

    term_.document_.body.appendChild(ttOverlay);
    term_.document_.body.appendChild(ttStatusArea);
    term_.document_.body.appendChild(ttOverlayStyleSheet);

    // If we can, make the terminal text better line up with the textarea text.
    if (term_.setScreenPaddingSize) {
        term_.setScreenPaddingSize(0);
    }
})();

```

Potential issues with this: 
 * Accessibility provided by hterm might not work with this.
 * The overlay currently only shows a single screenful of text at a time. What if the user wants to select more than what's on the screen?

</details>

**Edit:** See [this comment](https://github.com/holzschu/a-shell/issues/231#issuecomment-860035352) for a prototype that I think works better and takes a different approach.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
## Summary
 * In `vim`, `less`, and `man`:
     * Touchscreen vertical and horizontal swipes move the cursor.
 * Inertial/kinetic scrolling support
 * Horizontal swipes move the cursor on the command line
 * Gestures for selecting text unchanged

https://user-images.githubusercontent.com/46334387/121786571-66b9d900-cb75-11eb-83c3-4df8e2361476.MP4

## Notes
 * The connection between `gestures.js` and `hterm.html` is untested (limited access to a Mac, so unable to build a-Shell).

## To-do
 * [x] Multi-touch gestures (e.g. two-finger right swipe for tab)
  * Two-finger right swipe: `Tab`
  * Two-finger left swipe: `Escape`

Should fix #231

### CODE REVIEW

**Comment by holzschu** [comment]
That looks pretty cool, and much better than anything I could do.
Since you're so good with JS, I have a question for you: long-press on space moves the iOS cursor, and it's very convenient on small screens. I haven't been able to make it move the a-Shell cursor, mainly because I couldn't find the event it fires. Do you have any idea on how to address that?

**Comment by personalizedrefrigerator** [comment]
> I haven't been able to make it move the a-Shell cursor, mainly because I couldn't find the event it fires. Do you have any idea on how to address that?

I don't know how to address this either... I know `document.onselectionchange` gets fired as a result...
Maybe if we show and focus an invisible text overlay (filled with space characters) when the cursor starts moving **and**
 * (1) there isn't a touch/pointer event in progress
 * (2) the user didn't just press a key (i.e. left-arrow to move the cursor left)
 * (3) it's newly out-of-sync with the hterm cursor

If the above three conditions are satisfied, the user is _probably_ using the long-press-on-space feature. The invisible screen-sized grid of space characters could let us detect cursor movements to locations where no text exists...

**Comment by holzschu** [comment]
I've tested the PR, and I cannot see any difference with before. In vim, less and man, moving the finger on screen has no effect, or scrolls the entire screen up. Horizontal swipes on the command line have no effect, and clicking on the command line does not move the cursor to the point where I clicked anymore. 

I've tested with all PRs incorporated, on both an iPhone and an iPad.

I'm going to place a few debugging calls to check what's happening in `gesture.js`.

**Comment by personalizedrefrigerator** [comment]
> I've tested the PR, and I cannot see any difference with before. In vim, less and man, moving the finger on screen has no effect, or scrolls the entire screen up. Horizontal swipes on the command line have no effect, and clicking on the command line does not move the cursor to the point where I clicked anymore.

All my tests have been running gestures.js via jsc --in-window. There's probably a bug connecting gestures.js to hterm.

> clicking on the command line does not move the cursor to the point where I clicked anymore.

It looks like this issue was present before the PR...

**Comment by personalizedrefrigerator** [comment]
In terms of testing the PR, 
 * `window.gestures_` should only be defined if `initializeTerminalGestures` ran.
     * So, if `jsi --force-inspect -wc "window.gestures_"` doesn't display anything, then `initializeTerminalGestures` either threw an exception/had an error very early in the script or `initializeTerminalGestures` isn't being called...
 * Changing `DEBUG = false` to `DEBUG = true` near the top of `gestures.js` will enable alerts if an exception is thrown during (much of) the handling of pointer events.

Thank you for your patience!

**Comment by holzschu** [comment]
The JS function ` window.webkit.messageHandlers.aShell.postMessage('text');` sends back `text` to the Swift/C side of a-Shell, where it can be processed. In a-Shell, unknown text messages are displayed on the Console (which can be accessed from a Mac connected to the device, or from Xcode). 

Both methods (`jsi` and `postMessage`) give the same information: `initializeTerminalGestures` was not called. The line just before it in `script.js` was executed, so it seems the function was not defined when the interpreter was there. I'll keep investigating.

**Comment by holzschu** [comment]
I forgot to embed `gestures.js` inside the App, so of course it was not loaded. I'm sorry.
Now it's working. Pretty neat with `man`, I must say.

**Comment by personalizedrefrigerator** [comment]
I'm glad it's working!

> Question: are you OK with being mentionned in the credits function, and do you have a website that you want me to link (otherwise I can just put "https://github.com/personalizedrefrigerator")?

I am OK with being referenced in the credits function. Instead of linking to my website, I think it makes sense to link to my list of commits: https://github.com/holzschu/a-shell/commits?author=personalizedrefrigerator :).

If you don't think this makes sense, then just use https://github.com/personalizedrefrigerator. Thank you!

**Comment by holzschu** [comment]
Hi, I have a new question about gestures and scrolling. After a long vertical scrolling (think 3000 lines up), sometimes there is a tiny horizontal move (it can be the user repositioning their hand, for example). As it is, this small move ends the scrolling and moves the screen back to the bottom, so the entire scrolling is lost and the user has to scroll back up 3000 lines.

I've traced the issue to the function `handleHorizontal_()` calling `term_.scrollEnd();`. Do you have any suggestions on how to improve the behaviour? I'm thinking that horizontal moves should not call `term_.scrollEnd();`, but rather leave the screen as it is.

**Comment by personalizedrefrigerator** [comment]
> Hi, I have a new question about gestures and scrolling. After a long vertical scrolling (think 3000 lines up), sometimes there is a tiny horizontal move (it can be the user repositioning their hand, for example). As it is, this small move ends the scrolling and moves the screen back to the bottom, so the entire scrolling is lost and the user has to scroll back up 3000 lines.
> 
> I've traced the issue to the function `handleHorizontal_()` calling `term_.scrollEnd();`. Do you have any suggestions on how to improve the behaviour? I'm thinking that horizontal moves should not call `term_.scrollEnd();`, but rather leave the screen as it is.

I haven't tested it, but I think commenting out `term_.scrollEnd()` would be an acceptable fix — pressing the `←` button in the toolbar moves the cursor to the left without scrolling to the end, so the behavior would be consistent.

**Pull request merged**
