### PR TITLE
Changed Intents to run on background in-app; fixes #729

### LINKED ISSUE #729: Extension no longer has access to folders from `pickFolder`
I’m trying to build a shortcut that will do some git operations in another app’s sandbox. 
* I’ve used `pickFolder` to create a bookmark to that folder called `LogSeq`.
* I’m running a script to `cd` to that folder and do the work
* The script works when run in the full app, but doesn’t work in the extension
* I’ve tried using the full path to the folder instead of the bookmark. Neither way works
* I believe this used to work? I’m basing this belief off comments from people in the LogSeq community who used this workflow in the past, but I’ve never personally used it before.

IMG_0022

Thanks!

### PR DESCRIPTION
**Pull request by mdbraber**

### CODE REVIEW

**Comment by mdbraber** [comment]
@holzschu one part not included in this PR is the `localcommands` code: https://github.com/holzschu/a-shell/blob/master/a-Shell-Intents/IntentHandler.swift#L201. As commands can now be run 'broader' what would you suggest to use for this? As commands now would have access to configuration files or local library files (right?) we would mostly need to exclude non-interactive commands.

It can also be left to the user to not use any non-interactive commands and 'just' leave this code out. What do you think?

**Comment by holzschu** [comment]
Hi,
Thank you for this contribution. I'm reviewing the PR, and I'd like to be sure that I understand everything in the code before I merge. I have many questions for you, really in order to be sure.
- IntentHandler.swift has been split into three different files (ExecuteCommandIntentHandler.swift, PutFileIntentHandler.swift and GetFileIntentHandler.swift), and the choice between these three is done in AppDelegate?
- The user should have a choice between three options: running in Extension (light work, fast), running in App with visible output in the app, running in App with no visible feedback. And "keep going after an error" should still be an option (for all three). One way to do it would be for "Open the app to execute the commands?" to have more options in its pop-up menu: No (run in extension), No (run in background app), Yes. I'm not entirely sure about this, though.
- The Default behaviour is, as you said, another question. I don't think it should be the default to have the app running silently (for security issues, but also for debugging: if there are bugs in the script, the user should know). Once the script works well in the foreground, users can activate the "run in background app" version.
- I don't see anything in the code that is specific to more recent versions of iOS, but I have to ask: all of this works with iOS 14, right?

Thanks again for this contribution.

**Comment by mdbraber** [comment]
> * IntentHandler.swift has been split into three different files (ExecuteCommandIntentHandler.swift, PutFileIntentHandler.swift and GetFileIntentHandler.swift), and the choice between these three is done in AppDelegate?

Yes - this is in line with the WWDC instructions: https://developer.apple.com/wwdc20/10073. Although not strictly necessary I think this gives the best overview.

> * The user should have a choice between three options: running in Extension (light work, fast), running in App with visible output in the app, running in App with no visible feedback. And "keep going after an error" should still be an option (for all three). One way to do it would be for "Open the app to execute the commands?" to have more options in its pop-up menu: No (run in extension), No (run in background app), Yes. I'm not entirely sure about this, though.

I'm not sure if "Run in extension" would make any sense if there's already "run in background app". It's basically the same from the user perspective (run in background; no interaction) but with more relaxed time / memory limits. Theoretically "run in extension" could be an even more light weight / faster environment, but I'm thinking (no tests done) that the start time is very brief, but we should run some tests to be sure.

> * The Default behaviour is, as you said, another question. I don't think it should be the default to have the app running silently (for security issues, but also for debugging: if there are bugs in the script, the user should know). Once the script works well in the foreground, users can activate the "run in background app" version.

Yes agree - I think "run in the background" should not be the default.

> * I don't see anything in the code that is specific to more recent versions of iOS, but I have to ask: all of this works with iOS 14, right?

Haven't run any tests, but also did not change any of the compile settings afaik and it compiles for iOS14. Also in the WWDC video I think it's mentioned this is also working for iOS14.

**Comment by holzschu** [comment]
> I'm not sure if "Run in extension" would make any sense if there's already "run in background app". It's basically the same from the user perspective (run in background; no interaction) but with more relaxed time / memory limits. Theoretically "run in extension" could be an even more light weight / faster environment, but I'm thinking (no tests done) that the start time is very brief, but we should run some tests to be sure.

I agree with you that "Run in Extension" is not going to be the best choice, but we have to keep it for backwards compatibility: there are existing Shortcuts that rely on it, and I don't want to break them. Thank you for your answers, I'm now going to experiment with the PR on a side branch.

**Comment by mdbraber** [comment]
Thanks! Do you mean "Run in Extension" to be kept available as an option (from a UI perspective?) You could maybe keep the variable but not show it in the UI and give an error / message that the variable will be deleted in the future (I've seen other Shortcuts do that)

**Comment by holzschu** [comment]
The changes are now in the "localServer" branch. I'm uploading them to TestFlight. Thank you very much for your help here.

For the time being, I'm keeping the changes in the UI minimal, so "Run in extension" is kept as an option and is the default if the commands are not too complicated (I think it makes a difference on small devices). "Run in background" is the second option, and "Open the app" is the third. That should ensure that existing shortcuts continue to work (I hope), but future Shortcuts will make use of the new option. (I'll see if I can change the UI at a later point).

**Comment by chicheese** [comment]
Is this pushed to a-shell app currently? I'd love to use it with obsidian git for syncing with my private git repo.

**Comment by kpham123** [comment]
oddly enough, I'm using the testFlight A-shell app along with the tutorial here and not seeing any difference in A-shell backgrounding:
https://forum.obsidian.md/t/mobile-automatic-sync-with-github-on-ios-for-free-via-a-shell/46150/71

**Comment by holzschu** [comment]
> oddly enough, I'm using the testFlight A-shell app along with the tutorial here and not seeing any difference in A-shell backgrounding: https://forum.obsidian.md/t/mobile-automatic-sync-with-github-on-ios-for-free-via-a-shell/46150/71

The tutorial is very long, and "not seeing any differences in a-Shell backgrounding" is a very short description. I assume you are using a Shortcut. Could you describe what the observed behaviour is when running "In app", and what is the observed behaviour when running "In extension"? That might help me in understanding the issue. 

But keep in mind that iOS can decide to terminate any app running in the background, at any time, if it thinks it is using too many system resources.

**Pull request merged**
